### PR TITLE
Pattern-1 and Pattern-2 converted 

### PR DESCRIPTION
**Pull request by vihanga-liyanage**
Removed nginx in pattern-2. Tested for both compose and swarm.

### CODE REVIEW

**Comment by imesh** [comment]
@vihanga-liyanage Can you please provide a more detailed description on your changes?
Thanks

**Comment by lakwarus** [comment]
Basically remove nginx and work directly with docker host port mapping for local deployment via docker-compose. When deploying in docker swarm, docker load balancer will use. (no need to have separate nginx)

**Comment by vihanga-liyanage** [comment]
@imesh Sorry about that. Lakmal has explained it for me. Will do next time. :)

**Comment by imesh** [comment]
Thanks, Lakmal! 
@vihanga-liyanage It's fine! Just wanted to know why these changes were done. Thanks!

**Pull request merged**
